### ISSUE TITLE
Торрсервер-клиент выдаёт ошибку при поиске торрентов

### ISSUE THREAD

**Issue by Seamas73** [virserg/kodirepo#1]
При поиске торрентов торрсервер клиент выдаёт ошибку и торренты не находит
[kodi.new.log](https://github.com/virserg/kodirepo/files/14136565/kodi.new.log)

**Comment by virserg** [comment]
Исправлено в новой версии 0.6.6

**Comment by Seamas73** [comment]
В версии 0.6.6 поиск торрентов заработал, но я столкнулся с тем, что не могу добавить найденный торрент в список торрентов на торрсервер. Уже добавленные торренты нормально проигрываются.
[kodi.log](https://github.com/virserg/kodirepo/files/14150073/kodi.log)

**Comment by virserg** [comment]
Версия 0.6.7 должна работать.

**Comment by Seamas73** [comment]
Да, заработало, спасибо.

**Comment by virserg** [comment]
Пожалуйста.
